# Node.js / Express — generated by Zyte Deploy Platform
# Review the comments below and adjust for your project before committing.
# Detected Playwright — using system Chromium (bundled download skipped).

FROM node:20-bookworm-slim AS build
WORKDIR /app
COPY package*.json ./
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
RUN npm ci
COPY . .
# CSS/TS/bundle build step — remove the line below if your project has no build script
RUN npm run build --if-present

FROM node:20-bookworm-slim AS runtime
WORKDIR /app
# System Chromium for Playwright (its bundled download is skipped above).
RUN apt-get update && apt-get install -y --no-install-recommends \
      chromium fonts-liberation ca-certificates \
    && rm -rf /var/lib/apt/lists/*
ENV PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium
# Launch the browser with --no-sandbox --disable-setuid-sandbox in containers.
COPY package*.json ./
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
RUN npm ci --omit=dev
# Copy source and any build artifacts from the build stage.
# Adjust these COPY lines to match your project's directory structure.
COPY --from=build /app/src ./src
COPY --from=build /app/public ./public
COPY --from=build /app/server.js ./server.js
USER node
EXPOSE 3000
CMD ["node", "server.js"]